### ISSUE TITLE
doc on "how to build docs"

### ISSUE THREAD

**Issue by jowens** [gunrock/docs#14]
If I want to make changes to our docs, what do I have to do? Things like:
- Make sure your repo is up to date (`git pull`)
- When I deploy, it does ... what? Actually pushes my local changes to the web? But doesn't check anything in? I need to do that manually after I'm done?
- What is the purpose of the `build` directory?
- If I put a source file in location X, where does it end up in the final web hierarchy?
- When I deploy, what actually happens? Does it check stuff in? Does it immediately push a new version to the web? (How/when do I use `--source-only` and `--push-only`?)
- How do I mark a file in my local directory that I don't want to get pushed into the repo?
- Can I do a local build and see what my changes will look like?
- What is the repo branching strategy? (Is there only `master`?)
- If I totally screw up something, how do I revert to the previous version (make sure it appears on the web)?

**Comment by neoblizz** [comment]
https://github.com/gunrock/docs/blob/master/CHECKLIST.md
