### ISSUE TITLE
https://gunrock.github.io/docs/#/hive/ subesquent pages throw HTTP 404

### ISSUE THREAD

**Issue by milewan** [gunrock/docs#26]
Hello team,
I was examining https://gunrock.github.io/docs/#/hive/ site, trying to access workload specific data, however github appears to refer to non-existing page. How could I access the information?

Thanks
Michal Lewandowski
Intel Corp.

**Comment by neoblizz** [comment]
https://gunrock.github.io/docs/#/hive/ fixed.
